services:
  python_app:
    build: ./docker
    shm_size: '2gb'
    volumes:
      - ./hdf5/:/src/hdf5/
      - ./IsolatedSignLanguage/:/src/IsolatedSignLanguage/
      - ./Interpolation/:/src/Interpolation
      - ./ContinuousSignLanguage:/src/ContinuousSignLanguage/
      - ./csv/:/src/csv/
      - ./data/:/src/data/
      - ./csv_to_hdf5/src/:/src/csv_to_hdf5/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw
    container_name: python_handlangage
    stdin_open: true
    environment:
      - DISPLAY=host.docker.internal:0.0