version: "3"
services:
  python_app:
    build: ./docker
    shm_size: '2gb'
    volumes:
      - ./hdf5/:/src/hdf5/
      - ./IsolatedSignLanguage/:/src/IsolatedSignLanguage/
      - ./Interpolation/:/src/Interpolation
      - ./ContinuousSignLanguage:/src/ContinuousSignLanguage/
      - ./csv/:/src/csv/
      - ./csv_to_hdf5/src/:/src/csv_to_hdf5/
    container_name: python_handlangage
    stdin_open: true